### PR TITLE
update fvm_shared to master so we can handle the EVM actor type.

### PR DESCRIPTION
**Pull request by raulk**
This is unfortunate spooky action at distance, but I don't have the bandwidth to fix it at origin now.

### CODE REVIEW

**Comment by anorth** [comment]
I don't know much about how the bundler works, but shouldn't it use the `Type` enum from the builtin-actors repo instead of the FVM?

**Comment by Stebalien** [comment]
Want me to cut an actual fvm_shared release?

> I don't know much about how the bundler works, but shouldn't it use the Type enum from the builtin-actors repo instead of the FVM?

Unfortunately, no. That would introduce an awkward cyclic dependency (_multiple_ actors versions depend on the same bundler).

What I'd _like_ to do is to just not use the type in the bundler entirely, and have the user pass in an index and a name manually.

**Comment by anorth** [comment]
> Want me to cut an actual fvm_shared release?

Wanna wait for https://github.com/filecoin-project/ref-fvm/pull/716 first?

> What I'd like to do is to just not use the type in the bundler entirely, and have the user pass in an index and a name manually

SGTM

**Comment by Stebalien** [comment]
No longer needed.

**Pull request closed without merging**
